const schoolLinks = [
  {
    name: "Spanish Schoolhouse Tomball",
    url: "archives/school-sites/spanish-schoolhouse-tomball/index.html",
    liveUrl: "https://spanishschoolhouse.com/tomball/",
    note: "Local one-page mirror with downloaded assets; live links stay available for dynamic parts."
  },
  {
    name: "Esprit International School",
    url: "archives/school-sites/esprit-international-school/index.html",
    liveUrl: "https://www.espritinternationalschool.com/",
    note: "Local one-page mirror with downloaded assets; live links stay available for dynamic parts."
  }
];

const baseArtworks = [
  {id:"painted-unicorn",title:"Painted Unicorn",school:"Spanish School House",grade:"PreK-K",type:"Ceramic",themes:["animals","hearts","3d","name"],images:["1000001574.jpg","1000001572.jpg","1000001573.jpg"],note:"Painted ceramic unicorn with signature, hearts, bright color patches, and a dated underside."},
  {id:"love-you-mom-plate",title:"Love You Mom Plate",school:"Spanish School House",grade:"PreK-K",type:"Ceramic",themes:["mom","hearts","family","3d"],images:["1000001576.jpg"],note:"Decorated plate with family labels, hearts, and a message for mom."},
  {id:"pop-up-chicken",title:"Pop-Up Chicken",school:"Spanish School House",grade:"PreK-K",type:"Paper Craft",themes:["animals","3d","folded"],images:["1000001533.jpg","1000001538.jpg"],note:"Folded paper scene with a dimensional chicken shape and a mostly blank backing page."},
  {id:"tiny-flower-book",title:"Tiny Flower Book",school:"Spanish School House",grade:"PreK-K",type:"Mini Book",themes:["flowers","early-writing","stapled"],images:["1000001560.jpg","1000001563.jpg","1000001561.jpg","1000001559.jpg","1000001557.jpg","1000001564.jpg","1000001562.jpg","1000001565.jpg","1000001558.jpg","1000001579.jpg"],note:"Small stapled pages with flower drawings, page numbers, and early writing."},
  {id:"heart-card-family",title:"Heart Card with Family Drawing",school:"Spanish School House",grade:"PreK-K",type:"Card",themes:["hearts","family","early-writing"],images:["1000001586.jpg","1000001585.jpg"],note:"Pink folded heart card and companion heart note with figures, stickers, and handwriting."},
  {id:"abstract-heart-studies",title:"Abstract Heart Studies",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["hearts","abstract","color"],images:["1000001542.jpg","1000001543.jpg","1000001544.jpg","1000001534.jpg","1000001532.jpg"],note:"Loose watercolor, pastel, and marker studies built around large heart shapes and early marks."},
  {id:"blue-folder",title:"Blue Folder with Painted Insert",school:"Spanish School House",grade:"PreK-K",type:"Paper Craft",themes:["pattern","folded","early-writing"],images:["1000001587.jpg","1000001588.jpg"],note:"Blue construction-paper folder with a colorful painted insert and handwritten inside/back view."},
  {id:"small-canvas",title:"Small Blue and Red Canvas",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["canvas","abstract","framed"],images:["1000001581.jpg"],note:"Small framed canvas with a bold red surround and a vertical blue form held inside a loose white ground."},
  {id:"paper-character",title:"Paper Character Cutout",school:"Spanish School House",grade:"PreK-K",type:"Paper Craft",themes:["characters","cutout","early-writing"],images:["1000001552.jpg"],note:"Large cut-paper figure with crown-like shapes and an expressive face."},
  {id:"mothers-day",title:"Mother's Day Backing Page",school:"Spanish School House",grade:"PreK-K",type:"Card",themes:["mom","mothers-day","name"],images:["1000001546.jpg","1000001535.jpg"],note:"Back pages connected to a Mother's Day piece, including Penelope's name in marker."},
  {id:"summer-song",title:"Summer Song Page",school:"Spanish School House",grade:"PreK-K",type:"Mini Book",themes:["music","early-writing","hearts"],images:["1000001548.jpg"],note:"Small folded/lined page with color swatches, hearts, and summer song lettering."},
  {id:"purple-line-boats",title:"Purple Line Boats",school:"Spanish School House",grade:"PreK-K",type:"Drawing",themes:["shapes","early-art"],images:["1000001568.jpg"],note:"Early purple line drawing with repeated heart-like forms."},
  {id:"boot-house-face",title:"Boot House Face",school:"Spanish School House",grade:"PreK-K",type:"Drawing",themes:["portrait","early-writing"],images:["1000001577.jpg"],note:"Small folded drawing with a face and labels around boot/house."},
  {id:"rainbow-heart-valentine",title:"Rainbow Heart Valentine",school:"Spanish School House",grade:"PreK-K",type:"Card",themes:["hearts","valentine"],images:["1000001554.jpg"],note:"Colorful heart worksheet or card addressed from Penelope to Dani."},
  {id:"cutout-letter-figure",title:"Cutout Letter Figure",school:"Spanish School House",grade:"PreK-K",type:"Paper Craft",themes:["letter","cutout","early-writing"],images:["1000001589.jpg"],note:"Cut-paper figure and message fragments with Penelope's early lettering."},

  {id:"animal-grid",title:"Animal Grid Sketches",school:"Esprit International School",grade:"Grade 2-4",type:"Drawing",themes:["animals","nature","study"],images:["1000001537.jpg"],note:"Nine-panel pencil study with ocean, land, insects, weather, and animals."},
  {id:"spiderman",title:"Spider-Man Portrait",school:"Esprit International School",grade:"Grade 2-4",type:"Drawing",themes:["characters","portrait","marker"],images:["1000001531.jpg"],note:"Bold marker drawing of Spider-Man signed Opie."},
  {id:"dream-of-alice",title:"The Dream of Alice",school:"Esprit International School",grade:"Grade 2-4",type:"Drawing",themes:["imagination","story","characters"],images:["1000001569.jpg"],note:"Large rabbit-like figure with title lettering and dense line work."},
  {id:"hypnotized-skeleton",title:"Hypnotized Skeleton",school:"Esprit International School",grade:"Grade 3-4",type:"Drawing",themes:["skeleton","science","portrait"],images:["1000001539.jpg"],note:"Neon marker skeleton on black grid paper labeled hypnotized."},
  {id:"black-geometric-print",title:"Black Geometric Print",school:"Esprit International School",grade:"Grade 3-4",type:"Printmaking",themes:["pattern","geometry","print"],images:["1000001536.jpg"],note:"Mounted print with geometric and circular shapes, signed Penelope."},
  {id:"campbells-soup",title:"Campbell's Tomato Soup",school:"Esprit International School",grade:"Grade 3-4",type:"Mixed Media",themes:["pop-art","food","collage"],images:["1000001545.jpg"],note:"Campbell's tomato soup inspired mixed-media composition."},
  {id:"one-cute-cute",title:"One Cute Cute Landscape",school:"Esprit International School",grade:"Grade 2-4",type:"Drawing",themes:["landscape","pattern","color"],images:["1000001541.jpg"],note:"Colored pencil landscape with repeated 'one cute' text."},
  {id:"painted-canvas-scene",title:"Painted Canvas Scene",school:"Esprit International School",grade:"Grade 2-4",type:"Painting",themes:["canvas","color","story"],images:["1000001547.jpg"],note:"Colorful painted canvas with outlined forms and objects."},
  {id:"square-cubing-study",title:"Square and Cubing Study",school:"Esprit International School",grade:"Grade 4",type:"Schoolwork",themes:["math","drawing","notes"],images:["1000001582.jpg","1000001583.jpg","1000001584.jpg"],note:"Hand-drawn square/cube diagrams and number pattern notes, including dated sheets."},
  {id:"feelings-family-chart",title:"Feelings and Family Chart",school:"Esprit International School",grade:"Grade 1-2",type:"Schoolwork",themes:["family","writing","feelings"],images:["1000001578.jpg"],note:"Folded chart with family names and feeling labels."},
  {id:"letter-to-mom",title:"Letter to Mom",school:"Esprit International School",grade:"Grade 1-3",type:"Writing",themes:["mom","letter","family"],images:["1000001549.jpg"],note:"Handwritten letter describing mom as special and mentioning her hair by the blue house."},
  {id:"dad-and-penelope",title:"Dad and Penelope Cutout Scene",school:"Esprit International School",grade:"Grade 1-3",type:"Paper Craft",themes:["dad","family","cutout"],images:["1000001551.jpg","1000001550.jpg"],note:"Cutout scene and related letter/drawing for Dad and Penelope."},
  {id:"birthday-note-to-dad",title:"Birthday Note to Dad",school:"Esprit International School",grade:"Grade 1-3",type:"Writing",themes:["dad","birthday","letter"],images:["1000001553.jpg"],note:"Birthday letter from Penelope with small character drawings."},
  {id:"recipe-drawing",title:"Recipe Drawing",school:"Esprit International School",grade:"Grade 1-3",type:"Writing",themes:["food","writing"],images:["1000001567.jpg"],note:"Illustrated recipe or food idea with labeled ingredients."},
  {id:"photo-collage-trujillo",title:"Penelope Trujillo Photo Collage",school:"Spanish School House",grade:"PreK-K",type:"Collage",themes:["family","photos","animals"],images:["1000001566.jpg"],note:"Photo collage with pets, travel, handprints, and Penelope Trujillo lettering."},
  {id:"gold-photo-collage",title:"Gold Photo Collage",school:"Esprit International School",grade:"Grade 3-4",type:"Collage",themes:["photos","family","sparkle"],images:["1000001571.jpg"],note:"Large glitter-board photo collage with Penelope lettering and many family photos."},
  {id:"carry-my-heart",title:"Carry My Heart With You",school:"Spanish School House",grade:"PreK-K",type:"Keepsake",themes:["mom","hearts","keepsake"],images:["1000001556.jpg"],note:"Printed poem with Penelope heart keychain keepsake."},
  {id:"sequence-practice",title:"Sequence Practice",school:"Esprit International School",grade:"Grade 1-2",type:"Schoolwork",themes:["math","writing"],images:["1000001555.jpg"],note:"Worksheet prompt about sequences with Penelope's answer."},
  {id:"pizza-friday",title:"Pizza Friday Flyer",school:"Esprit International School",grade:"Grade 1-4",type:"School Memory",themes:["school-life","food"],images:["1000001575.jpg"],note:"School flyer kept as context for everyday school life."},
  {id:"penelope-black-paper",title:"Penelope on Black Paper",school:"Esprit International School",grade:"Grade 4",type:"Schoolwork",themes:["name"],images:["1000001540.jpg"],note:"Dark paper with faint Penelope and 4th lettering."},
  {id:"bird-branch-card",title:"Bird Branch Card",school:"Spanish School House",grade:"PreK-K",type:"Card",themes:["birds","flowers","nature"],images:["1000001596.jpg"],note:"Decorated card with printed birds, branches, leaves, and bright flower accents."},
  {id:"spelling-words-sheet",title:"My Spelling Words",school:"Esprit International School",grade:"Grade 1-2",type:"Schoolwork",themes:["writing","spelling","schoolwork"],images:["1000001623.jpg"],note:"Single spelling-test strip preserved as part of the early elementary schoolwork set."},
  {id:"family-frame-keepsake",title:"Family Frame Keepsake",school:"Spanish School House",grade:"PreK-K",type:"Keepsake",themes:["family","photos","name"],images:["1000001627.jpg"],note:"Painted flower-shaped picture frame with a family photo and bold lettering around the border."},
  {id:"planet-research-earth",title:"Planet Research: Earth",school:"Esprit International School",grade:"Grade 1-2",type:"Schoolwork",themes:["science","planet","writing"],images:["1000001608.jpg"],note:"Planet research worksheet on Earth with handwritten answers about orbit, day length, and moons."},
  {id:"claudia-cat-painting",title:"Claudia Cat Painting",school:"Esprit International School",grade:"Grade 1-3",type:"Painting",themes:["animals","cats","name"],images:["1000001599.jpg"],note:"Bright cat portrait painted across color-blocked squares, with the cat's face stretched vertically through the composition."}
];

const intakeGroups = [
  ["PXL_20260508_182915449.jpg", "PXL_20260508_182921775.jpg"],
  ["PXL_20260508_182940615.jpg"],
  ["PXL_20260508_183013402.jpg"],
  ["PXL_20260508_183030931.jpg", "PXL_20260508_183039578.jpg"],
  ["PXL_20260508_183124772.jpg", "PXL_20260508_183131508.jpg"],
  ["PXL_20260508_183148559.jpg", "PXL_20260508_183159085.jpg"],
  ["PXL_20260508_183217108.jpg", "PXL_20260508_183226931.jpg"],
  ["PXL_20260508_183248407.jpg"],
  ["PXL_20260508_183309679.jpg"],
  ["PXL_20260508_183331569.jpg"],
  ["PXL_20260508_183355358.jpg"],
  ["PXL_20260508_183413728.jpg", "PXL_20260508_183420032.jpg"],
  ["PXL_20260508_183438545.jpg"],
  ["PXL_20260508_183458119.jpg", "PXL_20260508_183507323.jpg"],
  ["PXL_20260508_183531490.jpg"],
  ["PXL_20260508_183553362.jpg"],
  ["PXL_20260508_183621220.jpg"],
  ["PXL_20260508_183659908.jpg"],
  ["PXL_20260508_183726845.jpg", "PXL_20260508_183741985.jpg"],
  ["PXL_20260508_183803253.jpg", "PXL_20260508_183813500.jpg"],
  ["PXL_20260508_183836784.jpg", "PXL_20260508_183846050.jpg"],
  ["PXL_20260508_185826165.jpg", "PXL_20260508_185837578.jpg", "PXL_20260508_185845250.jpg", "PXL_20260508_185850856.jpg", "PXL_20260508_185859986.jpg", "PXL_20260508_185907531.jpg", "PXL_20260508_185919473.jpg"],
  ["PXL_20260508_185936380.jpg"],
  ["PXL_20260508_185948757.jpg"],
  ["PXL_20260508_190002179.jpg", "PXL_20260508_190013896.jpg"],
  ["PXL_20260508_190041756.jpg", "PXL_20260508_190047282.jpg"],
  ["PXL_20260508_190102422.jpg", "PXL_20260508_190110502.jpg"],
  ["PXL_20260508_190126665.jpg", "PXL_20260508_190137718.jpg", "PXL_20260508_190147832.jpg", "PXL_20260508_190157155.jpg", "PXL_20260508_190206592.jpg"],
  ["PXL_20260508_190219715.jpg"],
  ["PXL_20260508_190249325.jpg"],
  ["PXL_20260508_190303716.jpg", "PXL_20260508_190311387.jpg", "PXL_20260508_190320087.jpg", "PXL_20260508_190331081.jpg", "PXL_20260508_190336884.jpg"],
  ["PXL_20260508_190355347.jpg", "PXL_20260508_190404887.jpg"],
  ["PXL_20260508_190420540.jpg", "PXL_20260508_190432089.jpg"],
  ["PXL_20260508_190448174.jpg"],
  ["PXL_20260508_190513645.jpg", "PXL_20260508_190525249.jpg"],
  ["PXL_20260508_190544629.jpg", "PXL_20260508_190552145.jpg"],
  ["PXL_20260508_190603951.jpg", "PXL_20260508_190611232.jpg"],
  ["PXL_20260508_190621637.jpg"],
  ["PXL_20260508_190647569.jpg", "PXL_20260508_190656706.jpg"],
  ["PXL_20260508_190714645.jpg", "PXL_20260508_190719939.jpg"],
  ["PXL_20260508_190734646.jpg"],
  ["PXL_20260508_190823615.jpg", "PXL_20260508_190833856.jpg"],
  ["PXL_20260508_190847234.jpg", "PXL_20260508_190858438.jpg", "PXL_20260508_190909603.jpg", "PXL_20260508_190917488.jpg"],
  ["PXL_20260508_190931552.jpg"],
  ["PXL_20260508_191111205.jpg"],
  ["PXL_20260508_191123987.jpg"],
  ["PXL_20260508_191217368.jpg"],
  ["PXL_20260508_191238398.jpg"],
  ["PXL_20260508_191407059.jpg"],
  ["PXL_20260508_191452216.jpg"],
  ["PXL_20260508_191547347.jpg", "PXL_20260508_191555111.jpg", "PXL_20260508_191601258.jpg", "PXL_20260508_191611814.jpg", "PXL_20260508_191621159.jpg", "PXL_20260508_191627650.jpg", "PXL_20260508_191635658.jpg", "PXL_20260508_191645420.jpg", "PXL_20260508_191656924.jpg", "PXL_20260508_191704787.jpg", "PXL_20260508_191713923.jpg", "PXL_20260508_191722680.jpg", "PXL_20260508_191728121.jpg", "PXL_20260508_191734041.jpg", "PXL_20260508_191740281.jpg", "PXL_20260508_191746900.jpg", "PXL_20260508_191753086.jpg", "PXL_20260508_191759895.jpg"],
  ["PXL_20260508_191855073.jpg"],
  ["PXL_20260508_191913618.jpg"],
  ["PXL_20260508_191932262.jpg", "PXL_20260508_191940231.jpg"],
  ["PXL_20260508_192028721.jpg"],
  ["PXL_20260508_192048743.jpg"],
  ["PXL_20260508_192055351.jpg"],
  ["PXL_20260508_192107795.jpg"],
  ["PXL_20260508_192127271.jpg"],
  ["PXL_20260508_192201770.jpg"],
  ["PXL_20260508_192255712.jpg"],
  ["PXL_20260508_192323946.jpg"],
  ["PXL_20260508_192405521.jpg"],
  ["PXL_20260508_192438415.jpg"],
  ["PXL_20260508_192505554.jpg", "PXL_20260508_192519472.jpg"],
  ["PXL_20260508_192535283.jpg"],
  ["PXL_20260508_193956044.jpg", "PXL_20260508_194001438.jpg"],
  ["PXL_20260508_194016313.jpg", "PXL_20260508_194023835.jpg"],
  ["PXL_20260508_194036212.jpg", "PXL_20260508_194047947.jpg", "PXL_20260508_194054305.jpg", "PXL_20260508_194104458.jpg"],
  ["PXL_20260508_194133153.jpg"],
  ["PXL_20260508_194149995.jpg"],
  ["PXL_20260508_194208596.jpg"],
  ["PXL_20260508_194221054.jpg"],
  ["PXL_20260508_194235056.jpg", "PXL_20260508_194237833.jpg", "PXL_20260508_194243577.jpg", "PXL_20260508_194247593.jpg", "PXL_20260508_194254406.jpg"],
  ["PXL_20260508_194317919.jpg", "PXL_20260508_194328271.jpg", "PXL_20260508_194337009.jpg"],
  ["PXL_20260508_194351292.jpg"],
  ["PXL_20260508_194403828.jpg", "PXL_20260508_194415177.jpg"],
  ["PXL_20260508_194428374.jpg", "PXL_20260508_194437790.jpg"],
  ["PXL_20260508_194450815.jpg", "PXL_20260508_194459959.jpg", "PXL_20260508_194507789.jpg", "PXL_20260508_194519477.jpg", "PXL_20260508_194529605.jpg"],
  ["PXL_20260508_194548624.jpg"],
  ["PXL_20260508_194601578.jpg", "PXL_20260508_194610603.jpg"],
  ["PXL_20260508_194644932.jpg"],
  ["PXL_20260508_194702995.jpg"]
];

const firstPassIntakeMetadata = [
  {title:"Teacher Thank-You Note and Floral Card",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["teacher","note","flowers"],note:"Folded floral note and a handwritten thank-you from a teacher saved with the early school keepsakes."},
  {title:"Sea Bands Study",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["ocean","animals","color"],note:"Small blue-and-yellow painting with simple sea-life silhouettes and dot details."},
  {title:"Color-Block Cat Drawing",school:"Spanish School House",grade:"PreK-K",type:"Drawing",themes:["cats","animals","color"],note:"Bright cat portrait divided into bold color blocks."},
  {title:"Jungle Cat Drawing",school:"Spanish School House",grade:"PreK-K",type:"Drawing",themes:["cats","animals","nature"],note:"Yellow cat drawing with a blank reverse side kept in the same group."},
  {title:"Blue Dot Canvas with Back View",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["canvas","blue","abstract"],note:"Blue-dot canvas photographed from the front and the back of the stretched frame."},
  {title:"Spiderweb Drawing Study",school:"Esprit International School",grade:"Grade 1-2",type:"Drawing",themes:["spiderweb","pattern","study"],note:"Finished spiderweb drawing alongside a lighter sketch or planning version."},
  {title:"Name Canvas Back and Pencil Sketch",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["canvas","name","sketch"],note:"Back view of a labeled canvas paired with a faint front sketch."},
  {title:"Early Worksheet Page",school:"Esprit International School",grade:"Grade 1-2",type:"Schoolwork",themes:["worksheet","writing"],note:"Single worksheet page preserved with the intake batch."},
  {title:"Body Club Page",school:"Esprit International School",grade:"Grade 1-2",type:"Schoolwork",themes:["writing","school-life"],note:"Lined page titled 'Body Club' from the school papers set."},
  {title:"Lined Writing Page",school:"Esprit International School",grade:"Grade 1-2",type:"Writing",themes:["writing","lined-paper"],note:"Dense lined writing page from the same paper stack."},
  {title:"Lined Writing Reverse",school:"Esprit International School",grade:"Grade 1-2",type:"Writing",themes:["writing","lined-paper"],note:"Companion reverse side or second page from the lined writing set."},
  {title:"Orange Painted Sheet",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["orange","paint","abstract"],note:"Orange painted page with a lighter marked reverse side."},
  {title:"Flower Print Strip",school:"Spanish School House",grade:"PreK-K",type:"Printmaking",themes:["flowers","print","paint"],note:"Long painted-and-printed strip featuring flower-like stamped forms."},
  {title:"Mouse Drawing Note",school:"Spanish School House",grade:"PreK-K",type:"Drawing",themes:["mouse","animals","note"],note:"Small mouse drawing paired with a short handwritten note fragment."},
  {title:"Handprint Heart Valentine",school:"Spanish School House",grade:"PreK-K",type:"Card",themes:["valentine","handprint","hearts"],note:"Heart-shaped valentine built from handprints on red paper."},
  {title:"Layered Heart Card",school:"Spanish School House",grade:"PreK-K",type:"Card",themes:["hearts","valentine","3d"],note:"Heart card with layered paper hearts and a tied string detail."},
  {title:"Paper Plate Heart Wreath",school:"Spanish School House",grade:"PreK-K",type:"Paper Craft",themes:["hearts","wreath","valentine"],note:"Heart-themed paper plate wreath with attached center note."},
  {title:"Dog Portrait on Pink",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["dogs","portrait","pink"],note:"Gray-and-white dog portrait against a pink ground."},
  {title:"Colorado Girl Canvas",school:"Esprit International School",grade:"Grade 1-2",type:"Painting",themes:["colorado","school-pride","canvas"],note:"Colorful 'Colorado Girl' canvas photographed from the front, with the back view grouped alongside it."},
  {title:"Canvas Back Signed Emmy",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["canvas","name"],note:"Rear canvas view marked with Emmy's name."},
  {title:"Spelling Words Foldout",school:"Esprit International School",grade:"Grade 1-2",type:"Schoolwork",themes:["spelling","writing","foldout"],note:"Folded spelling-words sheet photographed closed and open."},
  {title:"Framed Red Figure Painting",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["framed","figure","abstract"],note:"Framed painting of a simple red figure with the back shown in the second view."},
  {title:"Texas Flag and Yellow Animal Crafts",school:"Spanish School House",grade:"PreK-K",type:"Paper Craft",themes:["flag","animals","hearts"],note:"Grouped preschool crafts including a flag painting, rolled yellow animal figure, and valentine heart pages."},
  {title:"Pop-Up Heart Face Card",school:"Spanish School House",grade:"PreK-K",type:"Card",themes:["hearts","3d","face"],note:"Folded heart-themed face card with a dimensional center flap."},
  {title:"I Love You Cut-Paper Note",school:"Spanish School House",grade:"PreK-K",type:"Card",themes:["hearts","message","cut-paper"],note:"Simple note with an attached pink cut-paper heart."},
  {title:"Gold Kite and Spelling Test",school:"Esprit International School",grade:"Grade 1-2",type:"Schoolwork",themes:["kite","spelling","schoolwork"],note:"Gold kite craft stored with a perfect spelling test."},
  {title:"Photo Leaf Ornaments",school:"Spanish School House",grade:"PreK-K",type:"Keepsake",themes:["photo","ornament","leaves"],note:"Two small leaf ornaments, one with a photo and one with painted swirl detail."},
  {title:"Mixed-Media Rose and Name Page",school:"Spanish School House",grade:"PreK-K",type:"Paper Craft",themes:["flowers","rose","name"],note:"Collaged rose scene paired with a penciled name page."},
  {title:"Love Program and Spelling Tests",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["program","spelling","school-life"],note:"School event program grouped with several spelling test cards."},
  {title:"Rainbow Name Page",school:"Spanish School House",grade:"PreK-K",type:"Drawing",themes:["name","rainbow","color"],note:"Color-banded name page with bold crayon stripes."},
  {title:"Preschool Recognition Certificate",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["certificate","recognition"],note:"Certificate of recognition from the preschool years."},
  {title:"Sweet Treats Coloring and Father's Day Card",school:"Spanish School House",grade:"PreK-K",type:"Card",themes:["father's-day","cupcake","coloring"],note:"Cluster of preschool cards and coloring pages, including cupcake and Father's Day pieces."},
  {title:"Crayon Stripe Pages",school:"Spanish School House",grade:"PreK-K",type:"Drawing",themes:["crayon","stripes","study"],note:"Two lightly colored crayon studies with stripe and curve patterns."},
  {title:"Rocket Portrait and Pastel Abstract",school:"Spanish School House",grade:"PreK-K",type:"Mixed Media",themes:["rocket","abstract","paint"],note:"Rocket collage portrait paired with a loose pastel-and-paint abstract page."},
  {title:"Gold Animal Silhouette",school:"Spanish School House",grade:"PreK-K",type:"Collage",themes:["animals","silhouette"],note:"Gold animal silhouette mounted on a black background."},
  {title:"Rainbow Vase Flowers",school:"Spanish School House",grade:"PreK-K",type:"Drawing",themes:["flowers","vase","color"],note:"Vase of flowers against a rainbow-blocked background with a faint reverse side."},
  {title:"Dark Abstract and Vase Studies",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["abstract","flowers","vase"],note:"Small group of painted studies including a dark abstract panel and two vase drawings."},
  {title:"Winter Snowman Set",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["winter","snowman","photo"],note:"Snowman craft board and a ribboned photo keepsake made during winter school activities."},
  {title:"Chick Drawing",school:"Spanish School House",grade:"PreK-K",type:"Drawing",themes:["birds","chick","animals"],note:"Yellow chick drawing with a simple reverse-side number mark."},
  {title:"Handprint Bouquet",school:"Spanish School House",grade:"PreK-K",type:"Keepsake",themes:["flowers","handprint","gift"],note:"Bouquet arrangement built from colorful handprints."},
  {title:"Mother's Day Flower Card",school:"Spanish School House",grade:"PreK-K",type:"Card",themes:["mom","mother's-day","flowers"],note:"Bright pink Mother's Day flower card saved with a small sketch page."},
  {title:"Pink Card and Hand Flower Pages",school:"Spanish School House",grade:"PreK-K",type:"Card",themes:["mom","flowers","handprint"],note:"Mixed set of pink note pages and flower drawings addressed to mom."},
  {title:"Mother's Day Plate",school:"Spanish School House",grade:"PreK-K",type:"Ceramic",themes:["mom","mother's-day","hearts"],note:"Decorated plate with handwritten Mother's Day message and hearts."},
  {title:"Abstract Heart Painting",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["hearts","abstract","color"],note:"Small abstract painting built around a bright central heart form."},
  {title:"Picture Frame Keepsake",school:"Spanish School House",grade:"PreK-K",type:"Keepsake",themes:["frame","photo","name"],note:"Decorated keepsake frame with school portrait insert."},
  {title:"Yellow Family Photo Collage",school:"Spanish School House",grade:"PreK-K",type:"Collage",themes:["photos","family","collage"],note:"Yellow poster-board family collage packed with stickers and snapshots."},
  {title:"Red Family Photo Collage",school:"Spanish School House",grade:"PreK-K",type:"Collage",themes:["photos","family","collage"],note:"Red family collage board featuring a denser arrangement of cut photos."},
  {title:"Pink Photo Board",school:"Spanish School House",grade:"PreK-K",type:"Collage",themes:["photos","family","pink"],note:"Large hot-pink photo board decorated with small stickers."},
  {title:"Large Family Collage Board",school:"Spanish School House",grade:"PreK-K",type:"Collage",themes:["photos","family","keepsake"],note:"Large embellished family collage board with many photos and stickers."},
  {title:"Emmy Name Day Set",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["name","school-day","certificate"],note:"Grouped keepsakes from an Emmy-themed school day, including name labels, notes, certificate, spelling sheet, and Spanish reading pages."},
  {title:"Dog Portrait on Red Ground",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["dogs","portrait","red"],note:"Second dog portrait with flower detail on a darker red ground."},
  {title:"Gestural Paint Study",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["abstract","gesture","paint"],note:"Loose gestural painting with many overlapping brush marks."},
  {title:"Framed Pink-and-Teal Abstract",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["abstract","framed","pink"],note:"Framed abstract painting shown from the front and the back."},
  {title:"Color Block Lettering Study",school:"Spanish School House",grade:"PreK-K",type:"Drawing",themes:["letters","geometry","color"],note:"Bright marker-and-crayon lettering study arranged in blocks."},
  {title:"Cross and Name Card",school:"Spanish School House",grade:"PreK-K",type:"Card",themes:["cross","blue","name"],note:"Blue cross painting paired with a folded name card."},
  {title:"Purple Abstract Study",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["abstract","purple","paint"],note:"Layered purple-and-blue abstract panel."},
  {title:"Pink Relief Portrait",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["portrait","pink","canvas"],note:"Small textured portrait or face study on a pink-blue ground."},
  {title:"Painted Frame Piece",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["frame","paint","mixed-media"],note:"Painted framed piece with decorative marks and symbols."},
  {title:"Framed Color Study",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["framed","color","study"],note:"Framed color study with Emmy's name printed on the mount."},
  {title:"Padre's Day Handprint Flower",school:"Spanish School House",grade:"PreK-K",type:"Keepsake",themes:["father's-day","handprint","flowers"],note:"Handprint flower gift for father or parent, labeled for Padre's Day."},
  {title:"Red House Landscape",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["houses","landscape","sky"],note:"Small landscape with houses, birds, and a striped sky."},
  {title:"Light Wash Scene",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["pastel","scene","light"],note:"Very faint painted scene kept as part of the preschool work batch."},
  {title:"Blue Graduation Cap",school:"Spanish School House",grade:"PreK-K",type:"Keepsake",themes:["graduation","cap","school-memory"],note:"Small blue graduation cap photographed from two angles."},
  {title:"Blue Submarine Craft",school:"Spanish School House",grade:"PreK-K",type:"Paper Craft",themes:["submarine","blue","vehicle"],note:"Cut-paper blue submarine craft with porthole details."},
  {title:"Koala Mask",school:"Spanish School House",grade:"PreK-K",type:"Mask",themes:["animals","koala","mask"],note:"Koala face mask photographed from the front and back."},
  {title:"Spanish Class Hand Project",school:"Spanish School House",grade:"PreK-K",type:"Schoolwork",themes:["handprint","spanish","classwork"],note:"Hand-shaped Spanish vocabulary project mounted on brown paper, with the inside drawing shown in the second image."},
  {title:"Mixed Preschool Crafts Set",school:"Spanish School House",grade:"PreK-K",type:"Paper Craft",themes:["crafts","space","smiley"],note:"Grouped preschool craft pieces including a hand puppet, smiley fan, plate craft, and a starry night collage."},
  {title:"Teacher Note Sheet",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["teacher","note","assessment"],note:"Teacher note or assessment page with floral border."},
  {title:"Spanish Schoolhouse Diploma",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["diploma","graduation"],note:"Spanish Schoolhouse diploma for Emmy Trujillo."},
  {title:"Chuck E. Cheese Portrait",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["portrait","photo","drawing"],note:"Printed portrait card from Chuck E. Cheese."},
  {title:"Spanish Booklet Cover",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["booklet","school-year"],note:"Front cover of a Spanish Schoolhouse booklet."},
  {title:"School Report Pages",school:"Esprit International School",grade:"Grade 1-2",type:"Schoolwork",themes:["report","assessment","schoolwork"],note:"Assessment and report pages from Esprit, grouped together as one school packet."},
  {title:"Spanish Schoolhouse Packet",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["packet","school-year","report"],note:"School-year packet pages and written reflection from Spanish Schoolhouse."},
  {title:"Mother's Day Handprint Print",school:"Spanish School House",grade:"PreK-K",type:"Keepsake",themes:["mother's-day","handprint","flowers"],note:"Handprint Mother's Day print with purple and pink paint."},
  {title:"Pink Drink Drawing and Booklet",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["drink","booklet","school-year"],note:"Summer-drink drawing grouped with a preschool booklet cover."},
  {title:"Graduation Seal, Soccer Certificate, and Report Pages",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["graduation","certificate","report"],note:"Graduation seal, soccer-shots certificate, booklet cover, and report pages from the preschool years."},
  {title:"Bird Photo Card",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["bird","photo","nature"],note:"Photo card featuring a bright bird perched on a branch."},
  {title:"Emmy Trujillo Venezuela Cover",school:"Esprit International School",grade:"Grade 1-2",type:"Schoolwork",themes:["venezuela","cover","country-study"],note:"Project cover about Emmy Trujillo and Venezuela with a note page stored behind it."},
  {title:"Photo Booth Strip",school:"School Memory",grade:"All ages",type:"Keepsake",themes:["photos","family","keepsake"],note:"Printed photo booth strip saved with the family keepsakes."},
  {title:"Ice Castles Photo",school:"School Memory",grade:"All ages",type:"Keepsake",themes:["photos","family","outing"],note:"Family outing photo from Ice Castles kept in the archive as context memory."}
];

const intakeMetadataByFirstImage = {
  "PXL_20260508_182915449.jpg": {title:"Teacher Thank-You Note and Floral Card",artist:"Penelope Trujillo",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["teacher","note","flowers"],note:"Folded floral note and a handwritten thank-you from a teacher saved with the early school keepsakes."},
  "PXL_20260508_182940615.jpg": {title:"Sea Bands Study",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["ocean","animals","color"],note:"Small blue-and-yellow painting with simple sea-life silhouettes and dot details."},
  "PXL_20260508_183013402.jpg": {title:"Color-Block Cat Drawing",school:"Spanish School House",grade:"PreK-K",type:"Drawing",themes:["cats","animals","color"],note:"Bright cat portrait divided into bold color blocks."},
  "PXL_20260508_183030931.jpg": {title:"Jungle Cat Drawing",school:"Spanish School House",grade:"PreK-K",type:"Drawing",themes:["cats","animals","nature"],note:"Yellow cat drawing with a blank reverse side kept in the same group."},
  "PXL_20260508_183124772.jpg": {title:"Blue Dot Canvas with Back View",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["canvas","blue","abstract"],note:"Blue-dot canvas photographed from the front and the back of the stretched frame."},
  "PXL_20260508_183148559.jpg": {title:"Spiderweb Drawing Study",school:"Esprit International School",grade:"Grade 1-2",type:"Drawing",themes:["spiderweb","pattern","study"],note:"Finished spiderweb drawing alongside a lighter sketch or planning version."},
  "PXL_20260508_183217108.jpg": {title:"Penelope Name Canvas Back and Pencil Sketch",artist:"Penelope Trujillo",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["canvas","name","sketch"],note:"Back view of a labeled Penelope canvas paired with a faint front sketch."},
  "PXL_20260508_183248407.jpg": {title:"Early Worksheet Page",school:"Esprit International School",grade:"Grade 1-2",type:"Schoolwork",themes:["worksheet","writing"],note:"Single worksheet page preserved with the intake batch."},
  "PXL_20260508_183309679.jpg": {title:"Body Club Page",school:"Esprit International School",grade:"Grade 1-2",type:"Schoolwork",themes:["writing","school-life"],note:"Lined page titled 'Body Club' from the school papers set."},
  "PXL_20260508_183331569.jpg": {title:"Lined Writing Page",school:"Esprit International School",grade:"Grade 1-2",type:"Writing",themes:["writing","lined-paper"],note:"Dense lined writing page from the same paper stack."},
  "PXL_20260508_183355358.jpg": {title:"Lined Writing Reverse",school:"Esprit International School",grade:"Grade 1-2",type:"Writing",themes:["writing","lined-paper"],note:"Companion reverse side or second page from the lined writing set."},
  "PXL_20260508_183413728.jpg": {title:"Orange Painted Sheet",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["orange","paint","abstract"],note:"Orange painted page with a lighter marked reverse side."},
  "PXL_20260508_183438545.jpg": {title:"Flower Print Strip",school:"Spanish School House",grade:"PreK-K",type:"Printmaking",themes:["flowers","print","paint"],note:"Long painted-and-printed strip featuring flower-like stamped forms."},
  "PXL_20260508_183458119.jpg": {title:"Mouse Drawing Note",school:"Spanish School House",grade:"PreK-K",type:"Drawing",themes:["mouse","animals","note"],note:"Small mouse drawing paired with a short handwritten note fragment."},
  "PXL_20260508_183531490.jpg": {title:"Handprint Heart Valentine",school:"Spanish School House",grade:"PreK-K",type:"Card",themes:["valentine","handprint","hearts"],note:"Heart-shaped valentine built from handprints on red paper."},
  "PXL_20260508_183553362.jpg": {title:"Layered Heart Card",school:"Spanish School House",grade:"PreK-K",type:"Card",themes:["hearts","valentine","3d"],note:"Heart card with layered paper hearts and a tied string detail."},
  "PXL_20260508_183621220.jpg": {title:"Paper Plate Heart Wreath",school:"Spanish School House",grade:"PreK-K",type:"Paper Craft",themes:["hearts","wreath","valentine"],note:"Heart-themed paper plate wreath with attached center note."},
  "PXL_20260508_183659908.jpg": {title:"Dog Portrait on Pink",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["dogs","portrait","pink"],note:"Gray-and-white dog portrait against a pink ground."},
  "PXL_20260508_183726845.jpg": {title:"Colorado Girl Canvas",artist:"Penelope Trujillo",school:"Esprit International School",grade:"Grade 1-2",type:"Painting",themes:["colorado","school-pride","canvas"],note:"Colorful 'Colorado Girl' canvas photographed from the front, with the back view grouped alongside it."},
  "PXL_20260508_183803253.jpg": {title:"Spelling Words Foldout",school:"Esprit International School",grade:"Grade 1-2",type:"Schoolwork",themes:["spelling","writing","foldout"],note:"Folded spelling-words sheet photographed closed and open."},
  "PXL_20260508_183836784.jpg": {title:"Framed Red Figure Painting",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["framed","figure","abstract"],note:"Framed painting of a simple red figure with the back shown in the second view."},
  "PXL_20260508_185826165.jpg": {title:"Texas Flag and Yellow Animal Crafts",school:"Spanish School House",grade:"PreK-K",type:"Paper Craft",themes:["flag","animals","hearts"],note:"Grouped preschool crafts including a flag painting, rolled yellow animal figure, and valentine heart pages."},
  "PXL_20260508_185936380.jpg": {title:"Pop-Up Heart Face Card",school:"Spanish School House",grade:"PreK-K",type:"Card",themes:["hearts","3d","face"],note:"Folded heart-themed face card with a dimensional center flap."},
  "PXL_20260508_185948757.jpg": {title:"I Love You Cut-Paper Note",school:"Spanish School House",grade:"PreK-K",type:"Card",themes:["hearts","message","cut-paper"],note:"Simple note with an attached pink cut-paper heart."},
  "PXL_20260508_190002179.jpg": {title:"Gold Kite and Spelling Test",school:"Esprit International School",grade:"Grade 1-2",type:"Schoolwork",themes:["kite","spelling","schoolwork"],note:"Gold kite craft stored with a perfect spelling test."},
  "PXL_20260508_190041756.jpg": {title:"Photo Leaf Ornaments",school:"Spanish School House",grade:"PreK-K",type:"Keepsake",themes:["photo","ornament","leaves"],note:"Two small leaf ornaments, one with a photo and one with painted swirl detail."},
  "PXL_20260508_190102422.jpg": {title:"Mixed-Media Rose and Name Page",school:"Spanish School House",grade:"PreK-K",type:"Paper Craft",themes:["flowers","rose","name"],note:"Collaged rose scene paired with a penciled name page."},
  "PXL_20260508_190126665.jpg": {title:"Love Program and Spelling Tests",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["program","spelling","school-life"],note:"School event program grouped with several spelling test cards."},
  "PXL_20260508_190219715.jpg": {title:"Rainbow Name Page",school:"Spanish School House",grade:"PreK-K",type:"Drawing",themes:["name","rainbow","color"],note:"Color-banded name page with bold crayon stripes."},
  "PXL_20260508_190249325.jpg": {title:"Preschool Recognition Certificate",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["certificate","recognition"],note:"Certificate of recognition from the preschool years."},
  "PXL_20260508_190303716.jpg": {title:"Sweet Treats Coloring and Father's Day Card",school:"Spanish School House",grade:"PreK-K",type:"Card",themes:["father's-day","cupcake","coloring"],note:"Cluster of preschool cards and coloring pages, including cupcake and Father's Day pieces."},
  "PXL_20260508_190355347.jpg": {title:"Crayon Stripe Pages",school:"Spanish School House",grade:"PreK-K",type:"Drawing",themes:["crayon","stripes","study"],note:"Two lightly colored crayon studies with stripe and curve patterns."},
  "PXL_20260508_190420540.jpg": {title:"Rocket Portrait and Pastel Abstract",school:"Spanish School House",grade:"PreK-K",type:"Mixed Media",themes:["rocket","abstract","paint"],note:"Rocket collage portrait paired with a loose pastel-and-paint abstract page."},
  "PXL_20260508_190448174.jpg": {title:"Gold Animal Silhouette",school:"Spanish School House",grade:"PreK-K",type:"Collage",themes:["animals","silhouette"],note:"Gold animal silhouette mounted on a black background."},
  "PXL_20260508_190513645.jpg": {title:"Rainbow Vase Flowers",school:"Spanish School House",grade:"PreK-K",type:"Drawing",themes:["flowers","vase","color"],note:"Vase of flowers against a rainbow-blocked background with a faint reverse side."},
  "PXL_20260508_190544629.jpg": {title:"Dark Abstract Panel",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["abstract","paint","dark"],note:"Dark painted abstract panel shown with its reverse side."},
  "PXL_20260508_190603951.jpg": {title:"Vase Flowers Drawing",school:"Spanish School House",grade:"PreK-K",type:"Drawing",themes:["flowers","vase","color"],note:"Colorful vase-and-flower drawing preserved with a blank reverse view."},
  "PXL_20260508_190621637.jpg": {title:"Sombrero Coloring Page",school:"Spanish School House",grade:"PreK-K",type:"Drawing",themes:["sombrero","spanish","coloring"],note:"Sombrero coloring page from the Spanish Schoolhouse batch."},
  "PXL_20260508_190647569.jpg": {title:"Winter Snowman Set",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["winter","snowman","photo"],note:"Snowman craft board and a ribboned photo keepsake made during winter school activities."},
  "PXL_20260508_190714645.jpg": {title:"Chick Drawing",school:"Spanish School House",grade:"PreK-K",type:"Drawing",themes:["birds","chick","animals"],note:"Yellow chick drawing with a simple reverse-side number mark."},
  "PXL_20260508_190734646.jpg": {title:"Handprint Bouquet",school:"Spanish School House",grade:"PreK-K",type:"Keepsake",themes:["flowers","handprint","gift"],note:"Bouquet arrangement built from colorful handprints."},
  "PXL_20260508_190823615.jpg": {title:"Mother's Day Flower Card",school:"Spanish School House",grade:"PreK-K",type:"Card",themes:["mom","mother's-day","flowers"],note:"Bright pink Mother's Day flower card saved with a small sketch page."},
  "PXL_20260508_190847234.jpg": {title:"Pink Card and Hand Flower Pages",school:"Spanish School House",grade:"PreK-K",type:"Card",themes:["mom","flowers","handprint"],note:"Mixed set of pink note pages and flower drawings addressed to mom."},
  "PXL_20260508_190931552.jpg": {title:"Mother's Day Plate",school:"Spanish School House",grade:"PreK-K",type:"Ceramic",themes:["mom","mother's-day","hearts"],note:"Decorated plate with handwritten Mother's Day message and hearts."},
  "PXL_20260508_191111205.jpg": {title:"Abstract Heart Painting",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["hearts","abstract","color"],note:"Small abstract painting built around a bright central heart form."},
  "PXL_20260508_191123987.jpg": {title:"Picture Frame Keepsake",school:"Spanish School House",grade:"PreK-K",type:"Keepsake",themes:["frame","photo","name"],note:"Decorated keepsake frame with school portrait insert and back view."},
  "PXL_20260508_191217368.jpg": {title:"Yellow Family Photo Collage",school:"Spanish School House",grade:"PreK-K",type:"Collage",themes:["photos","family","collage"],note:"Yellow poster-board family collage packed with stickers and snapshots."},
  "PXL_20260508_191238398.jpg": {title:"Red Family Photo Collage",school:"Spanish School House",grade:"PreK-K",type:"Collage",themes:["photos","family","collage"],note:"Red family collage board featuring a denser arrangement of cut photos."},
  "PXL_20260508_191407059.jpg": {title:"Pink Photo Board",school:"Spanish School House",grade:"PreK-K",type:"Collage",themes:["photos","family","pink"],note:"Large hot-pink photo board decorated with small stickers."},
  "PXL_20260508_191452216.jpg": {title:"Large Family Collage Board",school:"Spanish School House",grade:"PreK-K",type:"Collage",themes:["photos","family","keepsake"],note:"Large embellished family collage board with many photos and stickers."},
  "PXL_20260508_191547347.jpg": {title:"Emmy Name Day Set",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["name","school-day","certificate"],note:"Grouped keepsakes from an Emmy-themed school day, including name labels, notes, certificate, spelling sheet, and Spanish reading pages."},
  "PXL_20260508_191855073.jpg": {title:"Dog Portrait on Red Ground",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["dogs","portrait","red"],note:"Second dog portrait with flower detail on a darker red ground."},
  "PXL_20260508_191913618.jpg": {title:"Gestural Paint Study",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["abstract","gesture","paint"],note:"Loose gestural painting with many overlapping brush marks."},
  "PXL_20260508_191932262.jpg": {title:"Framed Pink-and-Teal Abstract",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["abstract","framed","pink"],note:"Framed abstract painting shown from the front and the back."},
  "PXL_20260508_192028721.jpg": {title:"Color Block Lettering Study",school:"Spanish School House",grade:"PreK-K",type:"Drawing",themes:["letters","geometry","color"],note:"Bright marker-and-crayon lettering study arranged in blocks."},
  "PXL_20260508_192048743.jpg": {title:"Red Cross Landscape",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["cross","landscape","sky"],note:"Small red cross or tower landscape with blue sky and green details."},
  "PXL_20260508_192055351.jpg": {title:"Emilia Name Card",school:"Spanish School House",grade:"PreK-K",type:"Card",themes:["name","hearts","writing"],note:"Simple folded card with Emilia lettering and a heart."},
  "PXL_20260508_192107795.jpg": {title:"Purple Abstract Study",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["abstract","purple","paint"],note:"Layered purple-and-blue abstract panel."},
  "PXL_20260508_192127271.jpg": {title:"Pink Relief Portrait",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["portrait","pink","canvas"],note:"Small textured portrait or face study on a pink-blue ground."},
  "PXL_20260508_192201770.jpg": {title:"Painted Frame Piece",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["frame","paint","mixed-media"],note:"Painted framed piece with decorative marks and symbols."},
  "PXL_20260508_192255712.jpg": {title:"Framed Color Study",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["framed","color","study"],note:"Framed color study with Emmy's name printed on the mount."},
  "PXL_20260508_192323946.jpg": {title:"Padre's Day Handprint Flower",school:"Spanish School House",grade:"PreK-K",type:"Keepsake",themes:["father's-day","handprint","flowers"],note:"Handprint flower gift for father or parent, labeled for Padre's Day."},
  "PXL_20260508_192405521.jpg": {title:"Red House Landscape",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["houses","landscape","sky"],note:"Small landscape with houses, birds, and a striped sky."},
  "PXL_20260508_192438415.jpg": {title:"Light Wash Scene",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["pastel","scene","light"],note:"Very faint painted scene kept as part of the preschool work batch."},
  "PXL_20260508_192505554.jpg": {title:"Blue Graduation Cap",school:"Spanish School House",grade:"PreK-K",type:"Keepsake",themes:["graduation","cap","school-memory"],note:"Small blue graduation cap photographed from two angles."},
  "PXL_20260508_192535283.jpg": {title:"Blue Submarine Craft",school:"Spanish School House",grade:"PreK-K",type:"Paper Craft",themes:["submarine","blue","vehicle"],note:"Cut-paper blue submarine craft with porthole details."},
  "PXL_20260508_193956044.jpg": {title:"Koala Mask",school:"Spanish School House",grade:"PreK-K",type:"Mask",themes:["animals","koala","mask"],note:"Koala face mask photographed from the front and back."},
  "PXL_20260508_194016313.jpg": {title:"Spanish Class Hand Project",school:"Spanish School House",grade:"PreK-K",type:"Schoolwork",themes:["handprint","spanish","classwork"],note:"Hand-shaped Spanish vocabulary project mounted on brown paper, with the inside drawing shown in the second image."},
  "PXL_20260508_194036212.jpg": {title:"Mixed Preschool Crafts Set",school:"Spanish School House",grade:"PreK-K",type:"Paper Craft",themes:["crafts","space","smiley"],note:"Grouped preschool craft pieces including a hand puppet, smiley fan, plate craft, and a starry night collage."},
  "PXL_20260508_194133153.jpg": {title:"Teacher Note Sheet",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["teacher","note","assessment"],note:"Teacher note or assessment page with floral border."},
  "PXL_20260508_194149995.jpg": {title:"Spanish Schoolhouse Diploma",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["diploma","graduation"],note:"Spanish Schoolhouse diploma for Emmy Trujillo."},
  "PXL_20260508_194208596.jpg": {title:"Chuck E. Cheese Portrait",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["portrait","photo","drawing"],note:"Printed portrait card from Chuck E. Cheese."},
  "PXL_20260508_194221054.jpg": {title:"Spanish Booklet Cover",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["booklet","school-year"],note:"Front cover of a Spanish Schoolhouse booklet."},
  "PXL_20260508_194235056.jpg": {title:"School Report Pages",school:"Spanish School House",grade:"PreK-K",type:"Schoolwork",themes:["report","assessment","schoolwork"],note:"Assessment and report pages grouped together as one school packet."},
  "PXL_20260508_194317919.jpg": {title:"Spanish Schoolhouse Packet",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["packet","school-year","report"],note:"School-year packet pages and written reflection from Spanish Schoolhouse."},
  "PXL_20260508_194351292.jpg": {title:"Mother's Day Handprint Print",school:"Spanish School House",grade:"PreK-K",type:"Keepsake",themes:["mother's-day","handprint","flowers"],note:"Handprint Mother's Day print with purple and pink paint."},
  "PXL_20260508_194403828.jpg": {title:"Pink Drink Drawing and Booklet",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["drink","booklet","school-year"],note:"Summer-drink drawing grouped with a preschool booklet cover."},
  "PXL_20260508_194428374.jpg": {title:"Spanish Schoolhouse Report Spreads",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["booklet","report","school-year"],note:"Open report booklet spreads from the Spanish Schoolhouse school-year packet."},
  "PXL_20260508_194450815.jpg": {title:"Graduation Seal, Soccer Certificate, and Report Pages",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["graduation","certificate","report"],note:"Graduation seal, soccer-shots certificate, booklet cover, and report pages from the preschool years."},
  "PXL_20260508_194548624.jpg": {title:"Bird Photo Card",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["bird","photo","nature"],note:"Photo card featuring a bright bird perched on a branch."},
  "PXL_20260508_194601578.jpg": {title:"Emmy Trujillo Venezuela Cover",school:"Esprit International School",grade:"Grade 1-2",type:"Schoolwork",themes:["venezuela","cover","country-study"],note:"Project cover about Emmy Trujillo and Venezuela with a note page stored behind it."},
  "PXL_20260508_194644932.jpg": {title:"Photo Booth Strip",school:"School Memory",grade:"All ages",type:"Keepsake",themes:["photos","family","keepsake"],note:"Printed photo booth strip saved with the family keepsakes."},
  "PXL_20260508_194702995.jpg": {title:"Ice Castles Photo",school:"School Memory",grade:"All ages",type:"Keepsake",themes:["photos","family","outing"],note:"Family outing photo from Ice Castles kept in the archive as context memory."}
};

const secondPassIntakeGroups = [
  ["PXL_20260509_115528647.jpg"],
  ["PXL_20260509_115538912.jpg", "PXL_20260509_115547574.jpg", "PXL_20260509_115551150.jpg", "PXL_20260509_115556887.jpg"],
  ["PXL_20260509_115609917.jpg"],
  ["PXL_20260509_115621863.jpg", "PXL_20260509_115631146.jpg"],
  ["PXL_20260509_115639677.jpg"],
  ["PXL_20260509_115712301.jpg"],
  ["PXL_20260509_115729838.jpg"],
  ["PXL_20260509_115741680.jpg", "PXL_20260509_115754852.jpg"],
  ["PXL_20260509_115806764.jpg"],
  ["PXL_20260509_115819495.jpg"],
  ["PXL_20260509_115836182.jpg"],
  ["PXL_20260509_115905651.jpg", "PXL_20260509_115921618.jpg", "PXL_20260509_115931035.jpg"],
  ["PXL_20260509_115950916.jpg"],
  ["PXL_20260509_120009003.jpg"],
  ["PXL_20260509_120024990.jpg"],
  ["PXL_20260509_120038332.jpg"],
  ["PXL_20260509_120050676.jpg", "PXL_20260509_120105276.jpg"],
  ["PXL_20260509_120124433.jpg"],
  ["PXL_20260509_120136890.jpg", "PXL_20260509_120149525.jpg"],
  ["PXL_20260509_120205302.jpg", "PXL_20260509_120213655.jpg"],
  ["PXL_20260509_120243896.jpg"],
  ["PXL_20260509_120300299.jpg"],
  ["PXL_20260509_120313282.jpg"]
];

const secondPassMetadataByFirstImage = {
  "PXL_20260509_115528647.jpg": {title:"Textured Yellow Chick",artist:"Penelope Trujillo",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["animals","chick","texture","googly-eyes"],note:"A playful chick portrait built from broad yellow texture marks, googly eyes, and a tiny paper beak; the brushwork gives it a fuzzy, feathery personality."},
  "PXL_20260509_115538912.jpg": {title:"Mother's Day Flower Booklet",artist:"Penelope Trujillo",school:"Spanish School House",grade:"PreK-K",type:"Card",themes:["mom","mother's-day","flowers","writing"],note:"A four-view Mother's Day booklet with a petal-flower cover, heartfelt inside message, an 'I love U' puppy drawing, and a closing page calling Mom 'the queen of queens.' The writing is especially warm and proud here."},
  "PXL_20260509_115609917.jpg": {title:"Warm-Tone Wolf Coloring",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Coloring",themes:["animals","wolf","pattern","color"],note:"A symmetrical wolf coloring page finished in reds, oranges, and yellows. Penelope stayed inside a lot of the ornamental shapes, and the hot palette makes the face feel lively and intense."},
  "PXL_20260509_115621863.jpg": {title:"Winter House Canvas",artist:"Penelope Trujillo",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["winter","house","snowman","canvas"],note:"Front and back views of a winter canvas with a yellow house, snowman, evergreen tree, and snowfall against a bright blue sky. It has a sweet storybook feel and a confident use of seasonal symbols."},
  "PXL_20260509_115639677.jpg": {title:"Clase de Mexico Binder Cover",artist:"Penelope Trujillo",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["school","binder","spanish","cover"],note:"A class binder cover labeled for Penelope's Mexico year at Spanish Schoolhouse. It works as a strong anchor piece for the earlier school packet."},
  "PXL_20260509_115712301.jpg": {title:"Lion Coloring Sheet",artist:"Penelope Trujillo",school:"Spanish School House",grade:"PreK-K",type:"Coloring",themes:["animals","lion","coloring","name"],note:"A cheerful lion coloring page signed with Penelope's name. The overlapping rainbow scribble gives it the loose, energetic feel of early childhood color exploration."},
  "PXL_20260509_115729838.jpg": {title:"Penelope Name Practice Strip",artist:"Penelope Trujillo",school:"Spanish School House",grade:"PreK-K",type:"Schoolwork",themes:["name","writing","letters","spanish"],note:"A laminated-style name strip showing both block-letter matching and Penelope writing out 'Penelope Trujillo' herself. It captures a really nice moment of letter confidence."},
  "PXL_20260509_115741680.jpg": {title:"Costa Rica Flag Lacing Card",artist:"Penelope Trujillo",school:"Spanish School House",grade:"PreK-K",type:"Paper Craft",themes:["flag","costa-rica","lacing","paint"],note:"Front and back of a Costa Rica flag craft with painted stripes, a crest sticker, and yarn lacing. The threading and paint together make it feel both decorative and hands-on."},
  "PXL_20260509_115806764.jpg": {title:"Cotton Ball Rainbow",artist:"Penelope Trujillo",school:"Spanish School House",grade:"PreK-K",type:"Paper Craft",themes:["rainbow","cotton","3d","weather"],note:"A raised rainbow made from folded paper bands and cotton-ball clouds. The dimensional build is the standout here; it reads like a weather collage with real softness."},
  "PXL_20260509_115819495.jpg": {title:"United Baggage Tag Keepsake",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Keepsake",themes:["travel","tag","family-memory"],note:"A saved United baggage tag labeled with Penelope's name and a destination note. It feels more like a family memory marker than schoolwork, but it adds personal context."},
  "PXL_20260509_115836182.jpg": {title:"Geometric Shapes Collage",artist:"Penelope Trujillo",school:"Spanish School House",grade:"PreK-K",type:"Collage",themes:["geometry","shapes","spanish","paper"],note:"A 'Figuras Geometricas' collage using torn colored paper to fill numbered shapes. The torn edges give the math prompt a handmade, mosaic-like quality."},
  "PXL_20260509_115905651.jpg": {title:"Pretend Job Application Packet",artist:"Penelope Trujillo",school:"Esprit International School",grade:"Grade 1-3",type:"Writing",themes:["writing","job","application","schoolwork"],note:"A three-view pretend job application set: airline tag, employment form pages, and a recommendation letter. It shows imaginative role-play mixed with growing confidence in full-sentence writing and self-description."},
  "PXL_20260509_115950916.jpg": {title:"Soft Purple Abstract",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Painting",themes:["abstract","purple","paint"],note:"A soft lavender abstract painted in overlapping washes with Penelope's name along the edge. The color layering is subtle and calm compared with some of the louder pieces."},
  "PXL_20260509_120009003.jpg": {title:"Pastel Veil Study",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Painting",themes:["abstract","pastel","gesture","color"],note:"A softly layered vertical study in lavender, peach, and pale yellow. It reads more like an atmospheric abstract than a literal figure, with color doing most of the work."},
  "PXL_20260509_120024990.jpg": {title:"Pink Photo Collage Board",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Collage",themes:["photos","family","pink","school-memory"],note:"A bright pink photo-collage board featuring Penelope with a bird cutout, family snapshots, and tiny marker doodles. It reads like a cheerful scrapbook page with lots of personality."},
  "PXL_20260509_120038332.jpg": {title:"Orange Photo Collage Board",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Collage",themes:["photos","family","orange","school-memory"],note:"An orange collage board with two photo prints of Penelope and a sibling, plus loose marker portraits below. The contrast between real photos and drawn faces is especially charming."},
  "PXL_20260509_120050676.jpg": {title:"Split-Face Portrait Collage",artist:"Penelope Trujillo",school:"Esprit International School",grade:"Grade 2-4",type:"Collage",themes:["portrait","collage","identity","mixed-media"],note:"Front and back views of a carefully assembled split-face collage combining two portrait halves into one image. This is one of the strongest concept pieces in the set; the alignment idea is smart and visually striking, and the reverse documents the handmade construction."},
  "PXL_20260509_120124433.jpg": {title:"Spanish Schoolhouse Diploma",artist:"Penelope Trujillo",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["diploma","graduation","certificate"],note:"A graduation diploma from Spanish Schoolhouse presented to Penelope Trujillo. A nice milestone document to keep grouped with the preschool materials."},
  "PXL_20260509_120136890.jpg": {title:"Thanksgiving Turkey Painting",artist:"Penelope Trujillo",school:"Spanish School House",grade:"PreK-K",type:"Painting",themes:["thanksgiving","turkey","seasonal","paint"],note:"Front and back views of a Thanksgiving turkey project on a printed 'Dia de Accion de Gracias' sheet. The painted feathers and hand-labeled name make it feel like a classic holiday classroom piece."},
  "PXL_20260509_120205302.jpg": {title:"Spanish Progress Report Packet",artist:"Penelope Trujillo",school:"Spanish School House",grade:"PreK-K",type:"Schoolwork",themes:["report","assessment","schoolwork","spanish"],note:"Cover and inside spread of Penelope's Spanish Schoolhouse progress report, including teachers, letter and shape work, and classroom-development assessments. It adds valuable educational context to the art archive."},
  "PXL_20260509_120243896.jpg": {title:"Nutcracker Canvas",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Painting",themes:["nutcracker","holiday","canvas","glitter"],note:"A holiday-themed canvas with a bold red nutcracker, candy-like motifs, and glitter accents. The layered greens and metallic sparkle make it one of the more visually dense paintings."},
  "PXL_20260509_120300299.jpg": {title:"Fine Curves Practice Sheet",artist:"Penelope Trujillo",school:"Spanish School House",grade:"PreK-K",type:"Schoolwork",themes:["prewriting","lines","motor-skills","worksheet"],note:"A prewriting sheet practicing long curves and narrowing lines. It is simple, but it documents early fine-motor control really well."},
  "PXL_20260509_120313282.jpg": {title:"Birthday Letter with Duck Drawing",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Card",themes:["birthday","writing","duck","family"],note:"An open birthday note filled with Penelope's handwriting, a duck sketch, and affectionate messages. It feels spontaneous, funny, and very personal in the best way."}
};

const thirdPassIntakeGroups = [
  ["PXL_20260509_142537711.jpg"],
  ["PXL_20260509_142549332.jpg", "PXL_20260509_142557869.jpg"],
  ["PXL_20260509_142640360.jpg", "PXL_20260509_142652362.jpg", "PXL_20260509_142700363.jpg", "PXL_20260509_142709533.jpg"],
  ["PXL_20260509_142729470.jpg"],
  ["PXL_20260509_142741002.jpg", "PXL_20260509_142752076.jpg"],
  ["PXL_20260509_142758720.jpg"],
  ["PXL_20260509_142811959.jpg", "PXL_20260509_142820770.jpg"],
  ["PXL_20260509_142838951.jpg"],
  ["PXL_20260509_142908419.jpg", "PXL_20260509_142922828.jpg"]
];

const thirdPassMetadataByFirstImage = {
  "PXL_20260509_142537711.jpg": {title:"Sock Puppet",artist:"Penelope Trujillo",school:"Spanish School House",grade:"PreK-K",type:"Puppet",themes:["sock","puppet","3d","googly-eyes"],note:"A handmade sock puppet with googly eyes, black yarn hair, and a felt mouth. It has a lot of personality for such a simple build, especially in the expressive hair and face placement."},
  "PXL_20260509_142549332.jpg": {title:"Library Visit Story Pages",artist:"Penelope Trujillo",school:"Esprit International School",grade:"Grade 1-3",type:"Writing",themes:["library","story","field-trip","writing"],note:"Two pages from a handwritten story about a library visit, classmates, books, lunch, and a scavenger hunt. The pages feel lively and conversational, and the smiling face on the second page gives the piece extra charm."},
  "PXL_20260509_142640360.jpg": {title:"Leaf Booklet",artist:"Penelope Trujillo",school:"Esprit International School",grade:"Grade 1-3",type:"Mini Book",themes:["leaves","nature","science","booklet"],note:"A four-view leaf booklet with labeled pages for leaf types, crayon leaf rubbings, and a flower landscape. It is a nice mix of observation, teacher-supported vocabulary, and decorative nature drawing."},
  "PXL_20260509_142729470.jpg": {title:"Colorful Love Drawing",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Drawing",themes:["love","hearts","portrait","color"],note:"A lively mixed-color drawing built around the word 'love,' hearts, and a stylized face. The bold crayon color choices make it feel spontaneous and joyful."},
  "PXL_20260509_142741002.jpg": {title:"Cardboard Bear Bag",artist:"Penelope Trujillo",school:"Spanish School House",grade:"PreK-K",type:"Paper Craft",themes:["bear","bag","3d","school-project"],note:"Front and back views of a cardboard-bag bear project with a face on one side and Spanish writing on the other. The bag format makes it feel like part costume, part classroom craft."},
  "PXL_20260509_142758720.jpg": {title:"Soft Multicolor Abstract",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Painting",themes:["abstract","paint","soft-color"],note:"A soft abstract painting with pink, green, blue, and earth-tone brush bands. The broad strokes feel exploratory and gentle rather than tightly planned."},
  "PXL_20260509_142811959.jpg": {title:"Alphabet Name Sheet",artist:"Penelope Trujillo",school:"Spanish School House",grade:"PreK-K",type:"Schoolwork",themes:["alphabet","name","writing","letters"],note:"Two related handwriting sheets practicing the alphabet and Penelope's name. They capture an early-learning moment where letter forms and self-identification come together."},
  "PXL_20260509_142838951.jpg": {title:"Portrait with Framing Hands",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Portrait",themes:["portrait","hands","drawing","self-expression"],note:"A careful portrait drawing framed by two open hands. The pose is unusually confident and composed, and the face and sweater pattern show more deliberate portrait thinking."},
  "PXL_20260509_142908419.jpg": {title:"Favorite Color and Shape Chart",artist:"Emmy Trujillo",school:"Spanish School House",grade:"Kindergarten",type:"Schoolwork",themes:["chart","colors","shapes","classroom"],note:"Two views of Emmy's kindergarten class chart listing children's favorite colors and favorite shapes. This belongs with Emmy's Spanish Schoolhouse materials rather than Penelope's later work."}
};

const fourthPassIntakeGroups = [
  ["PXL_20260509_143930454.jpg", "PXL_20260509_143936740.jpg"],
  ["PXL_20260509_144012616.jpg", "PXL_20260509_144020401.jpg", "PXL_20260509_144029935.jpg", "PXL_20260509_144038766.jpg", "PXL_20260509_144050060.jpg", "PXL_20260509_144103132.jpg", "PXL_20260509_144111717.jpg", "PXL_20260509_144121556.jpg", "PXL_20260509_144132069.jpg", "PXL_20260509_144141430.jpg", "PXL_20260509_144149450.jpg", "PXL_20260509_144158044.jpg", "PXL_20260509_144210971.jpg"]
];

const fourthPassMetadataByFirstImage = {
  "PXL_20260509_143930454.jpg": {title:"Te Amo Papa Wooden Tag",artist:"Emmy Trujillo",school:"Spanish School House",grade:"PreK-K",type:"Keepsake",themes:["dad","wood","painted","tag"],note:"Two views of a small painted wooden keepsake: one side reads 'Te Amo PAPA' and the other is labeled 'Emmy.' It feels like a sweet Father's Day or family-love gift from Emmy's early Spanish Schoolhouse years."},
  "PXL_20260509_144012616.jpg": {title:"Penelope Spelling Tests and Practice Set",artist:"Penelope Trujillo",school:"Esprit International School",grade:"Grade 1-3",type:"Schoolwork",themes:["spelling","tests","writing","schoolwork"],note:"A grouped run of Penelope spelling practice sheets and tests, including perfect scores, corrected papers, and several 8/10 and 9/10 results. Per your note, these were part of the Chiller Bee reward rhythm, which makes the whole set feel like a strong record of growth, correction, and consistency rather than just isolated quizzes."}
};

const fifthPassIntakeGroups = [
  ["1000001838.jpg"],
  ["1000001839.jpg"],
  ["1000001840.jpg"],
  ["1000001841.jpg", "1000001842.jpg"],
  ["1000001843.jpg"],
  ["1000001844.jpg"],
  ["1000001845.jpg"],
  ["1000001846.jpg"],
  ["1000001847.jpg"],
  ["1000001848.jpg", "1000001864.jpg"],
  ["1000001849.jpg"],
  ["1000001850.jpg"],
  ["1000001851.jpg"],
  ["1000001852.jpg"],
  ["1000001854.jpg", "1000001855.jpg"],
  ["1000001856.jpg"],
  ["1000001857.jpg", "1000001859.jpg"],
  ["1000001858.jpg"],
  ["1000001860.jpg"],
  ["1000001861.jpg", "1000001862.jpg", "1000001863.jpg"],
  ["1000001865.jpg"],
  ["1000001866.jpg"],
  ["1000001867.jpg"],
  ["1000001868.jpg"],
  ["1000001869.jpg"],
  ["1000001870.jpg"],
  ["1000001871.jpg"],
  ["1000001872.jpg"],
  ["1000001873.jpg"],
  ["1000001874.jpg"],
  ["1000001875.jpg"],
  ["1000001876.jpg", "1000001877.jpg", "1000001878.jpg", "1000001879.jpg", "1000001880.jpg", "1000001881.jpg", "1000001882.jpg", "1000001883.jpg", "1000001884.jpg", "1000001885.jpg", "1000001886.jpg"],
  ["1000001887.jpg"],
  ["1000001853.jpg"]
];

const fifthPassMetadataByFirstImage = {
  "1000001838.jpg": {title:"Bold Geometric Color Study",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Mixed Media",themes:["abstract","cardboard","marker","color"],note:"A bright cardboard color study with layered diagonal bands and the word Penelope built into the composition. It pairs nicely with the other cardboard experiments in this batch."},
  "1000001839.jpg": {title:"All the You Birthday Card Front",artist:"Unknown",school:"School Memory",grade:"All ages",type:"Card",themes:["birthday","card","hello-kitty","keepsake"],note:"The decorated front of a birthday card saved with Penelope's materials. It belongs in the archive as a received keepsake rather than a classroom assignment."},
  "1000001840.jpg": {title:"ExpoArte Spanish Schoolhouse Certificate",artist:"Emmy Trujillo",school:"Spanish School House",grade:"PreK-K",type:"School Memory",themes:["certificate","expoarte","spanish-schoolhouse","art-show"],note:"A Spanish Schoolhouse ExpoArte certificate for Emmy Trujillo, documenting her artist statement for the butterfly artwork 'Borboleta.'"},
  "1000001841.jpg": {title:"Birthday Card to Penelope",artist:"Mila",school:"School Memory",grade:"All ages",type:"Card",themes:["birthday","card","friendship","keepsake"],note:"Front and inside views of a birthday card addressed to Penelope and signed by Mila. The inside includes a small star drawing and a sweet handwritten birthday message."},
  "1000001843.jpg": {title:"Lower Elementary Crushes Map",artist:"Penelope Trujillo",school:"Esprit International School",grade:"Grade 1-3",type:"School Memory",themes:["friends","classmates","map","lower-elementary"],note:"A very specific Lower Elementary 2025 friendship-and-crushes map, with names, arrows, and notes. It is more social artifact than formal schoolwork, and that makes it a great archive piece."},
  "1000001844.jpg": {title:"Dear Mom Brightest Light Letter",artist:"Penelope Trujillo",school:"School Memory",grade:"Grade 1-3",type:"Writing",themes:["mom","letter","gratitude","family"],note:"A faint pencil letter to mom with lines about hope, love, and being the brightest light. The writing is delicate, so the cleaned image preserves the full page context."},
  "1000001845.jpg": {title:"Purple Hello Emmy Note",artist:"Emmy Trujillo",school:"School Memory",grade:"PreK-K",type:"Drawing",themes:["hello","emmy","early-writing","purple-paper"],note:"An early purple-paper note with large red marks and a small green drawing. The uneven torn edge and exploratory marks are part of the charm."},
  "1000001846.jpg": {title:"Hello Emmy Dog Photo Collage",artist:"Emmy Trujillo",school:"School Memory",grade:"PreK-K",type:"Collage",themes:["dog","photo","hello","family"],note:"A purple-paper collage with a dog photo and handwritten 'Hello Emmy' lettering. It reads like a home memory piece more than classroom work."},
  "1000001847.jpg": {title:"Clean House To-Do List",artist:"Penelope Trujillo",school:"School Memory",grade:"Grade 1-3",type:"Writing",themes:["to-do-list","chores","play","home"],note:"A handwritten list for cleaning the house, including nap time, reading, play with Legos, and crayon markers. It captures the funny seriousness of a kid-made household plan."},
  "1000001848.jpg": {title:"Cardboard Line and Color Study",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Mixed Media",themes:["cardboard","abstract","marker","color"],note:"Two related photos of a cardboard abstract with bold diagonal marker lines and mint, blue, red, and purple color fields."},
  "1000001849.jpg": {title:"Belantsea Extinct Sea Creature Report",artist:"Penelope Trujillo",school:"Esprit International School",grade:"Grade 1-3",type:"Schoolwork",themes:["report","sea-creature","writing","science"],note:"A creature report for the imagined or researched Belantsea, complete with a drawing, extinct label, habitat line, and descriptive notes about movement and body features."},
  "1000001850.jpg": {title:"Living Whale Drawing",artist:"Penelope Trujillo",school:"Esprit International School",grade:"Grade 1-3",type:"Schoolwork",themes:["whale","living","science","drawing"],note:"A pencil whale drawing with the word 'Living' in large letters underneath. It likely belongs with the creature-report sequence."},
  "1000001851.jpg": {title:"Penelope Color Blocks",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Painting",themes:["watercolor","abstract","blocks","color"],note:"A signed watercolor built from overlapping color blocks, dark washes, and white crayon-resist marks."},
  "1000001852.jpg": {title:"Blue and Green Watercolor Field",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Painting",themes:["watercolor","blue","green","abstract"],note:"A broad blue-green watercolor field with a quiet open center and brighter green at the top edge."},
  "1000001854.jpg": {title:"Penelope Landscape Resist Painting",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Painting",themes:["watercolor","landscape","crayon-resist","penelope"],note:"Front and back views of a signed watercolor landscape with blue, green, yellow, and purple bands plus white resist marks."},
  "1000001856.jpg": {title:"Soft Animal Mark Study",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Painting",themes:["animal","marks","minimal","watercolor"],note:"A very light signed mark study with scattered soft gray shapes and a small green mark near the top."},
  "1000001857.jpg": {title:"Penelope Bird Watercolor Pair",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Painting",themes:["bird","watercolor","crayon","color"],note:"Two signed watercolor-and-line pieces that read as bird or creature studies, both with layered washes and energetic black linework."},
  "1000001858.jpg": {title:"Black and White Bunny Portrait",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Drawing",themes:["bunny","animal","marker","portrait"],note:"A close animal portrait with long ears, black patches, and a warm peach nose. The simple linework gives it a strong character."},
  "1000001860.jpg": {title:"Reindeer Head Drawing",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Drawing",themes:["reindeer","animal","marker","holiday"],note:"A close-up reindeer head with antlers and bold black outline, photographed as a single finished drawing."},
  "1000001861.jpg": {title:"Woodlands Town Center Trolley Toy",artist:"Family Archive",school:"School Memory",grade:"The Woodlands Years",type:"Keepsake",themes:["woodlands","trolley","toy","town-center"],note:"Three views of a green Woodlands Town Center Trolley toy. It is included as a place-memory object from the girls' Woodlands years rather than as a drawn artwork."},
  "1000001865.jpg": {title:"Standing Figure in Striped Pants",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Drawing",themes:["figure","fashion","marker","portrait"],note:"A long standing figure drawing with striped pants, raised hands, and a small head, likely part of the same imaginative character run as the Astrid/Jungle Boys sheets."},
  "1000001866.jpg": {title:"Eiffel Tower Dress Drawing",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Drawing",themes:["eiffel-tower","fashion","architecture","drawing"],note:"A detailed dress or tower hybrid with Eiffel-like structure, decorative panels, and careful crosshatching."},
  "1000001867.jpg": {title:"Numbered Plate Dinner Plan",artist:"Penelope Trujillo",school:"School Memory",grade:"Grade 1-3",type:"Drawing",themes:["menu","plate","food","numbered-list"],note:"A kid-made plate diagram with a numbered food list including ketchup, fork, knife, drink, place mat, and chicken."},
  "1000001868.jpg": {title:"Train and Help Drawing",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Drawing",themes:["train","transportation","help","sketch"],note:"A pencil-and-marker transportation drawing with a large train-like form and the word 'HELP' integrated into the image."},
  "1000001869.jpg": {title:"Girl by the Red House",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Drawing",themes:["girl","house","colored-pencil","portrait"],note:"A colored-pencil scene of a girl standing between a green outdoor area and a red house-like form."},
  "1000001870.jpg": {title:"Notre-Dame Office Sketch",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Drawing",themes:["notre-dame","office","map","imagination"],note:"A dense pencil sketch labeled with Notre-Dame and office-like elements, arranged like an architectural plan or imaginative destination map."},
  "1000001871.jpg": {title:"Banana Coffee Note",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Drawing",themes:["banana","coffee","note","early-writing"],note:"A playful page with banana and coffee labels, a simple cup drawing, and early writing around the page."},
  "1000001872.jpg": {title:"Astrid Jungle Boys Drawing",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Drawing",themes:["astrid","jungle","character","drawing"],note:"A character sheet labeled Astrid and Jungle Boys, with a central figure and extra marks around the edges."},
  "1000001873.jpg": {title:"Two Faces Study",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Portrait",themes:["faces","portrait","ink","character"],note:"A black-ink face study with a large central head and a smaller full-body figure at the side."},
  "1000001874.jpg": {title:"Anything Can Be Art Sketchbook Spread",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Sketchbook",themes:["sketchbook","chocolate","anything-can-be-art","drawing"],note:"An open sketchbook spread with a turtle or animal drawing, chocolate label, and the phrase 'Anything can be art.'"},
  "1000001875.jpg": {title:"City Towers and Cloud Drawing",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Drawing",themes:["city","buildings","cloud","architecture"],note:"A cityscape drawing with tall clustered buildings, a large cloud shape, and repeated window grids. The duplicate Pixel capture from this batch was skipped."},
  "1000001876.jpg": {title:"Marlene's How to Draw Animals",artist:"Marlene",school:"Family Archive",grade:"Childhood",type:"Mini Book",themes:["animals","drawing-book","childhood","family"],note:"A handmade childhood booklet by Marlene titled 'How to Draw Animals,' photographed from cover through step-by-step pages for fish, whale, cat, ostrich, ant, parakeet, camel, guinea pig, and panda. The pages preserve her early sequencing and playful animal instructions."},
  "1000001887.jpg": {title:"Marlene at New Mexico Tech, 2006",artist:"Dad",school:"Family Archive",grade:"New Mexico Tech, 2006",type:"Drawing",themes:["mom","dad","portrait","college","family"],note:"A portrait drawing of Marlene made by Dad while at New Mexico Tech in 2006. The archive note keeps the family context directly attached to the image so it stays easy to find later."},
  "1000001853.jpg": {title:"Green and Brown Abstract Painting",artist:"Penelope Trujillo",school:"School Memory",grade:"All ages",type:"Painting",themes:["watercolor","abstract","green","brown"],note:"A signed abstract with earthy brown, green, purple, and blue washes crossed by loose black linework."}
};

const allIntakeGroups = [...intakeGroups, ...secondPassIntakeGroups, ...thirdPassIntakeGroups, ...fourthPassIntakeGroups, ...fifthPassIntakeGroups];
const allIntakeMetadataByFirstImage = {...intakeMetadataByFirstImage, ...secondPassMetadataByFirstImage, ...thirdPassMetadataByFirstImage, ...fourthPassMetadataByFirstImage, ...fifthPassMetadataByFirstImage};
const emmyIntakeFirstImages = new Set([
  "PXL_20260508_191547347.jpg",
  "PXL_20260508_191855073.jpg",
  "PXL_20260508_191913618.jpg",
  "PXL_20260508_191932262.jpg",
  "PXL_20260508_192028721.jpg",
  "PXL_20260508_192048743.jpg",
  "PXL_20260508_192055351.jpg",
  "PXL_20260508_192107795.jpg",
  "PXL_20260508_192127271.jpg",
  "PXL_20260508_192201770.jpg",
  "PXL_20260508_192255712.jpg",
  "PXL_20260508_192323946.jpg",
  "PXL_20260508_192405521.jpg",
  "PXL_20260508_192438415.jpg",
  "PXL_20260508_192505554.jpg",
  "PXL_20260508_192535283.jpg",
  "PXL_20260508_193956044.jpg",
  "PXL_20260508_194016313.jpg",
  "PXL_20260508_194036212.jpg",
  "PXL_20260508_194133153.jpg",
  "PXL_20260508_194149995.jpg",
  "PXL_20260508_194208596.jpg",
  "PXL_20260508_194221054.jpg",
  "PXL_20260508_194235056.jpg",
  "PXL_20260508_194317919.jpg",
  "PXL_20260508_194351292.jpg",
  "PXL_20260508_194403828.jpg",
  "PXL_20260508_194428374.jpg",
  "PXL_20260508_194450815.jpg",
  "PXL_20260508_194548624.jpg",
  "PXL_20260508_194601578.jpg"
]);

const intakeArtworks = allIntakeGroups.map((images, index) => {
  const count = String(index + 1).padStart(2, "0");
  const meta = allIntakeMetadataByFirstImage[images[0]] || firstPassIntakeMetadata[index];
  return {
    id: `intake-batch-${count}`,
    artist: meta.artist || (emmyIntakeFirstImages.has(images[0]) ? "Emmy Trujillo" : "Penelope Trujillo"),
    ...meta,
    images
  };
});

const normalizeSchool = (school) => {
  if (school === "Spanish School House") return "Spanish Schoolhouse Tomball";
  if (school === "Spanish Schoolhouse") return "Spanish Schoolhouse Tomball";
  return school;
};

const inferPeriod = (item) => {
  const school = normalizeSchool(item.school);
  if (school === "Spanish Schoolhouse Tomball") return "Early Childhood";
  if (school === "Esprit International School") return "Elementary Years";
  return "Family Archive";
};

const archiveDefaults = (item) => ({
  ...item,
  artist: item.artist || "Penelope Trujillo",
  school: normalizeSchool(item.school),
  period: item.period || inferPeriod(item)
});

const artworks = [...baseArtworks, ...intakeArtworks].map(archiveDefaults);
